# Setup
title:               Tell Me Something Unique About You
tagline:             'Tell me something unique about you'
description:         'Collection of notes written by students about themselves'
url:                 'https://www.gastonsanchez.com'
baseurl:             '/tell-me-something-unique-about-you'

# About/contact
author:
  name:              Gaston Sanchez
  url:               https://www.gastonsanchez.com

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: 

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor


